### PR TITLE
Add docs about seeding random generator

### PR DESCRIPTION
**Pull request by mooreryan**
I added a short note regarding seeding random number generator.  Feel free to reword or ignore if you don't think it is necessary!

### CODE REVIEW

**Comment by c-cube** [comment]
Maybe a word about `Random.self_init()` as an example of how to seed the generator would also help? :)

**Comment by mooreryan** [comment]
Sure, I can add an example later today.

**Comment by mooreryan** [comment]
I added an example, did a little reorg where the seeding stuff is now in its own section, and added another header to the section so the TOC looks something like this:

toc

**Comment by c-cube** [comment]
thank you!

**Pull request merged**
